# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:

- task: CocoaPods@0
  inputs:
    forceRepoUpdate: true
  displayName: 'pod install using the CocoaPods task with defaults'

- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'FranvaroAppen'
    sdk: 'iphoneos'
    configuration: 'Debug' #Release
    xcWorkspacePath: 'FranvaroAppen.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath


